# Colors (Tomorrow Night Bright)
[colors.primary]
background = '#000000'
foreground = '#eaeaea'

[colors.normal]
black = '#000000'
red = '#d54e53'
green = '#b9ca4a'
yellow = '#e6c547'
blue = '#7aa6da'
magenta = '#c397d8'
cyan = '#70c0ba'
white = '#424242'

[colors.bright]
black = '#666666'
red = '#ff3334'
green = '#9ec400'
yellow = '#e7c547'
blue = '#7aa6da'
magenta = '#b77ee0'
cyan = '#54ced6'
white = '#2a2a2a'

[window]
startup_mode = "Maximized"

[font]
size = 14.0

[font.bold]
family = "MesloLGM Nerd Font"

[font.bold_italic]
family = "MesloLGM Nerd Font"

[font.italic]
family = "MesloLGM Nerd Font"

[font.normal]
family = "MesloLGM Nerd Font"

[terminal.shell]
program = "/opt/homebrew/bin/fish"
